"""
🏗️ Architecture — Voltown Code Reference
==========================================
A beautiful, structured reference for students to understand and
replicate the Voltown sequential decision framework in their own projects.
"""

import streamlit as st
import inspect
import textwrap

st.set_page_config(page_title="Architecture", page_icon="🏗️", layout="wide")

# ═══════════════════════════════════════════════════════════════════════
# Page header
# ═══════════════════════════════════════════════════════════════════════

st.markdown("""
# 🏗️ Architecture Reference

> **Everything you need to replicate this framework in your own project.**
>
> This page documents the code structure, interfaces, and design decisions
> behind the Voltown sequential-decision dashboard.  Read this *before*
> you start building — it will save you hours.
""")

st.divider()

# ═══════════════════════════════════════════════════════════════════════
# 1. Architectural Map — Mermaid Pipeline
# ═══════════════════════════════════════════════════════════════════════

st.header("1 · Architectural Map")

st.markdown("""
The system is a **5-module pipeline**.  Data flows left-to-right:
the Oracle generates reality, the Forecast approximates it,
Policies decide, the Simulator executes, and Analytics visualise.
""")

st.markdown("""
```mermaid
graph LR
    subgraph Engine
        A["🌍 Oracle<br/><code>world.py</code>"]
        B["🔮 Forecast<br/><code>forecast.py</code>"]
        C["🧠 Policy<br/><code>policies.py</code>"]
        D["⚡ Simulator<br/><code>simulator.py</code>"]
    end

    subgraph Frontend
        E["📊 Analytics<br/><code>pages/*.py</code>"]
    end

    A -- "W: dict<br/>demand, price, solar" --> D
    A -- "W_history" --> B
    B -- "W_forecast: dict<br/>shape (paths, H)" --> C
    C -- "X: dict<br/>5 flow variables" --> D
    D -- "Episode result<br/>costs, battery, decisions" --> E

    style A fill:#f5f7fa,stroke:#e74c3c,color:#333
    style B fill:#f5f7fa,stroke:#f39c12,color:#333
    style C fill:#f5f7fa,stroke:#2ecc71,color:#333
    style D fill:#f5f7fa,stroke:#3498db,color:#333
    style E fill:#f5f7fa,stroke:#9b59b6,color:#333
```
""")

# Interface contracts compact table
st.markdown("#### Interface Contracts at Each Arrow")

contracts_md = """
| Edge | Sender | Receiver | Data Shape |
|------|--------|----------|------------|
| W → Simulator | `world.py` | `simulator.py` | `{'demand': array(T), 'price': array(T), 'solar': array(T)}` |
| W_history → Forecast | `simulator.py` | `forecast.py` | `{'demand': array(t), 'price': array(t), 'solar': array(t)}` |
| W_forecast → Policy | `forecast.py` | `policies.py` | `{'demand': array(P,H), 'price': array(P,H), 'solar': array(P,H)}` |
| X → Simulator | `policies.py` | `simulator.py` | `{'x_gb': float, 'x_sb': float, 'x_sd': float, 'x_bd': float, 'x_gd': float}` |
| Result → Analytics | `simulator.py` | `pages/` | `{'costs': array(T), 'battery': array(T+1), 'decisions': list, 'total_cost': float}` |
"""
st.markdown(contracts_md)

st.divider()

# ═══════════════════════════════════════════════════════════════════════
# 2. Data Structures
# ═══════════════════════════════════════════════════════════════════════

st.header("2 · Data Structures")

st.markdown("""
Four core data structures flow through the system.  Every module
speaks the same language — this is what makes the pipeline composable.
""")

col1, col2 = st.columns(2)

with col1:
    st.subheader("W — Exogenous Information")
    st.markdown("""
    The *world* at each period. Generated by `world.py`,
    consumed by policies and the simulator.
    """)
    st.code("""
# Full episode (T periods)
W = {
    'demand': np.array([3.1, 2.8, ...]),  # shape (T,)
    'price':  np.array([0.12, 0.14, ...]),  # shape (T,)
    'solar':  np.array([0.0, 1.2, ...]),  # shape (T,)
}

# Single period (extracted in simulation loop)
W_t = {
    'demand': 3.1,   # scalar — kWh demanded
    'price':  0.12,  # scalar — $/kWh grid cost
    'solar':  2.5,   # scalar — kWh available for free
}
""", language="python")

    st.subheader("WorldParams — Environment Config")
    st.markdown("Dataclass controlling the ground-truth stochastic process.")
    st.code("""
@dataclass
class WorldParams:
    T: int = 24              # Periods per episode
    K: float = 10.0          # Battery capacity (kWh)
    R_init: float = 2.0      # Initial battery level
    cycles: int = 2          # Sinusoidal peaks per episode

    # Demand
    demand_base:  float = 3.0
    demand_amp:   float = 1.5
    demand_noise: float = 0.4

    # Grid price
    price_base:  float = 0.12
    price_amp:   float = 0.04
    price_noise: float = 0.008

    # Solar
    solar_amp:   float = 4.0
    solar_noise: float = 0.4
""", language="python")

with col2:
    st.subheader("X — Decision Vector")
    st.markdown("""
    The 5 energy-flow variables returned by *every* policy.
    These are the **decision variables** of the MDP.
    """)
    st.code("""
X = {
    'x_gb': 2.0,  # Grid → Battery (charge)
    'x_sb': 1.5,  # Solar → Battery (store)
    'x_sd': 1.0,  # Solar → Demand (use directly)
    'x_bd': 0.5,  # Battery → Demand (discharge)
    'x_gd': 0.3,  # Grid → Demand (buy & use)
}
""", language="python")

    st.markdown("""
    ```mermaid
    graph LR
        G["⚡ Grid"] -- "x_gb" --> B["🔋 Battery"]
        S["☀️ Solar"] -- "x_sb" --> B
        S -- "x_sd" --> D["🏠 Demand"]
        B -- "x_bd" --> D
        G -- "x_gd" --> D

        style G fill:#f5f7fa,stroke:#e74c3c,color:#333
        style S fill:#f5f7fa,stroke:#f1c40f,color:#333
        style B fill:#f5f7fa,stroke:#2ecc71,color:#333
        style D fill:#f5f7fa,stroke:#3498db,color:#333
    ```
    """)

    st.subheader("Episode Result — Simulation Output")
    st.markdown("Returned by `run_episode()` for analytics downstream.")
    st.code("""
result = {
    'costs':      np.array([...]),   # shape (T,) — per-period costs
    'battery':    np.array([...]),   # shape (T+1,) — battery trajectory
    'decisions':  [X_0, X_1, ...],  # list of T decision dicts
    'total_cost': 2.34,             # scalar — sum of costs
}
""", language="python")

st.divider()

# ═══════════════════════════════════════════════════════════════════════
# 3. Policy Interface Contract
# ═══════════════════════════════════════════════════════════════════════

st.header("3 · Policy Interface Contract")

st.markdown("""
**The most important design decision in the whole system.**

Every policy — no matter how simple or complex — must conform to
one of two signatures.  This is what makes the tournament possible:
the simulator doesn't know *how* a policy decides, only that it
returns a valid decision dict.
""")

col_std, col_dla = st.columns(2)

with col_std:
    st.markdown("#### Standard Policies (PFA, CFA, VFA)")
    st.code("""
def policy_fn(R_t: float,
              W_t: dict,
              params: dict) -> dict:
    '''
    Maps current state to decision.

    Args:
        R_t:    Battery level (kWh), the state variable
        W_t:    Current exogenous info {demand, price, solar}
        params: Policy-specific parameters + K

    Returns:
        X: Decision dict with 5 flow variables
           {'x_gb', 'x_sb', 'x_sd', 'x_bd', 'x_gd'}
    '''
    # ... policy logic ...
    return {'x_gb': ..., 'x_sb': ..., 'x_sd': ...,
            'x_bd': ..., 'x_gd': ...}
""", language="python")

with col_dla:
    st.markdown("#### DLA Policies (need forecast)")
    st.code("""
def policy_DLA(R_t: float,
               W_t: dict,
               W_forecast: dict,
               params: dict) -> dict:
    '''
    Maps state + forecast to decision.

    Args:
        R_t:        Battery level (kWh)
        W_t:        Current exogenous info
        W_forecast: Forecasted future W
                    - Deterministic: {key: array(H)}
                    - Stochastic: {key: array(P, H)}
        params:     Policy parameters + K + horizon

    Returns:
        X: Decision dict (same 5 keys)
    '''
    # ... solve multi-period LP ...
    # ... return ONLY period-0 decision ...
    return {'x_gb': ..., 'x_sb': ..., 'x_sd': ...,
            'x_bd': ..., 'x_gd': ...}
""", language="python")

st.info("""
**🔑 The key invariant:** Policies are **pure functions**.
They receive state, return decisions. No side effects, no internal memory,
no mutation.  This makes them testable, composable, and swappable.
""", icon="🔑")

st.divider()

# ═══════════════════════════════════════════════════════════════════════
# 4. Gym-like Environment Analogy
# ═══════════════════════════════════════════════════════════════════════

st.header("4 · OpenAI Gym Analogy")

st.markdown("""
If you've used OpenAI Gym / Gymnasium, the Voltown framework follows the
same structure.  The table below maps concepts 1:1.
""")

gym_md = """
| OpenAI Gym | Voltown Equivalent | Module |
|---|---|---|
| `env = gym.make('CartPole-v1')` | `W = generate_W(params, seed)` | `world.py` |
| `obs = env.reset()` | `R = R_init; W_t = W[0]` | `simulator.py` |
| `action = agent.act(obs)` | `X = policy_fn(R_t, W_t, params)` | `policies.py` |
| `obs, reward, done, info = env.step(action)` | `R_next = transition(R, X, K)`; `cost = period_cost(X, W_t)` | `mdp.py` |
| `reward` | `-period_cost` *(negative: we minimise cost)* | `mdp.py` |
| `env.render()` | Plotly charts in `pages/` | `pages/*.py` |
| Training loop | `run_episode()` / `run_tournament()` | `simulator.py` |
| Hyperparameters | `params` dict (θ values) | `policies.py` |
"""
st.markdown(gym_md)

st.markdown("#### The Core Loop (both frameworks)")

col_gym, col_vol = st.columns(2)

with col_gym:
    st.markdown("**OpenAI Gym**")
    st.code("""
obs = env.reset()
done = False
while not done:
    action = agent.act(obs)
    obs, reward, done, _ = env.step(action)
    total_reward += reward
""", language="python")

with col_vol:
    st.markdown("**Voltown**")
    st.code("""
R = R_init
for t in range(T):
    W_t = {k: v[t] for k, v in W.items()}
    X = policy_fn(R, W_t, params)
    cost = period_cost(X, W_t)
    R = transition(R, X, K)
    total_cost += cost
""", language="python")

st.divider()

# ═══════════════════════════════════════════════════════════════════════
# 5. Module Source Code
# ═══════════════════════════════════════════════════════════════════════

st.header("5 · Module Source Code")

st.markdown("""
The full source of every engine module, loaded live from disk.
Click any expander to read the implementation.
""")

# Import modules for source inspection
from engine import world, mdp, policies, simulator, forecast, vfa_training

modules = [
    ("🌍 world.py — Exogenous Information Generator", world,
     "Generates ground-truth demand/price/solar sequences. Contains `WorldParams` dataclass and both normal + Extremistan generators."),
    ("⚙️ mdp.py — Transition & Cost Functions", mdp,
     "The physics of the battery system: `transition()` clips battery state, `period_cost()` computes grid energy cost."),
    ("🔮 forecast.py — Naive Forecast Engine", forecast,
     "Generates forecast scenarios for DLA policies. Intentionally simple — demonstrates that even naive forecasts enable anticipation."),
    ("🧠 policies.py — All Policy Implementations", policies,
     "All 9 policies across Powell's 4 classes, plus `POLICY_REGISTRY` and `CLASS_COLORS`. The heart of the system."),
    ("⚡ simulator.py — Episode Runner & Tournament", simulator,
     "The main simulation loop: `run_episode()` connects policy → MDP → recording. `run_tournament()` compares policies over many seeds."),
    ("📈 vfa_training.py — VFA Training Algorithms", vfa_training,
     "Value Iteration, Q-Learning, and ADP training. Discretization helpers define the state/action space."),
]

for title, mod, description in modules:
    with st.expander(title, expanded=False):
        st.caption(description)
        try:
            source = inspect.getsource(mod)
            st.code(source, language="python", line_numbers=True)
        except (OSError, TypeError):
            st.warning(f"Could not read source for {mod.__name__}")

st.divider()

# ═══════════════════════════════════════════════════════════════════════
# 6. How to Extend
# ═══════════════════════════════════════════════════════════════════════

st.header("6 · How to Extend (for Student Projects)")

st.markdown("""
The modular design makes it straightforward to extend.
Here are the four most common extension paths:
""")

col_a, col_b = st.columns(2)

with col_a:
    st.success("""
    **➕ To add a new policy:**

    1. Write `policy_fn(R_t, W_t, params) → X`
    2. Add an entry to `POLICY_REGISTRY` in `policies.py`
    3. That's it — the simulator and dashboard pick it up automatically

    ```python
    def policy_myidea(R_t, W_t, params):
        # Your clever logic here
        return {'x_gb': ..., 'x_sb': ..., 'x_sd': ...,
                'x_bd': ..., 'x_gd': ...}
    ```
    """, icon="✅")

    st.info("""
    **📊 To add analytics:**

    The tournament returns a `pd.DataFrame` where:
    - Each column = a policy name
    - Each row = an episode's total cost

    Add your own Plotly charts in a new `pages/` file.
    The simulator output is your data source.
    """, icon="📊")

with col_b:
    st.warning("""
    **🔧 To change the problem:**

    Modify two files:
    - `world.py` — change the W generator
      (different distributions, correlations, seasonality)
    - `mdp.py` — change the transition/cost functions
      (different physics, multiple resources, penalties)

    All policies automatically adapt if the interface stays the same.
    """, icon="🔧")

    st.info("""
    **🧪 To add a training algorithm:**

    1. Implement your trainer in `vfa_training.py`
       (returns trained artifact: weights, Q-table, etc.)
    2. Write a policy function that uses the artifact
    3. Register with `'needs_training': 'your_method'`
       in `POLICY_REGISTRY`
    """, icon="🧪")

st.markdown("---")

st.markdown("""
> **🏛️ The Architectural Invariant**
>
> *Policies are pure functions. They receive state, return decisions. No side effects.*
>
> This invariant enables: reproducible experiments, parallel tournament runs,
> fair comparisons, and clean analytics.  **Never break it.**
""")

st.divider()

# ═══════════════════════════════════════════════════════════════════════
# 7. Powell's Framework Recap — 2×2 Taxonomy
# ═══════════════════════════════════════════════════════════════════════

st.header("7 · Powell's Policy Taxonomy — The 2×2 Framework")

st.markdown("""
Warren Powell's universal framework classifies **all** sequential
decision policies along two dimensions:
""")

col_dim1, col_dim2 = st.columns(2)

with col_dim1:
    st.markdown("""
    #### Dimension 1: Policy vs. Value
    - **Policy-based** — directly map state → decision *(what to do)*
    - **Value-based** — learn a value function, decide greedily *(what's it worth)*
    """)

with col_dim2:
    st.markdown("""
    #### Dimension 2: Lookahead
    - **No lookahead** — decide using only current information
    - **With lookahead** — optimise over a model of the future
    """)

st.markdown("#### The 2×2 Taxonomy")

# Render the taxonomy as a styled markdown table
st.markdown("""
|  | **No Lookahead** | **With Lookahead** |
|---|---|---|
| **Policy-based** | 🔴 **PFA** — Policy Function Approximation | 🟣 **DLA** — Direct Lookahead Approximation |
| **Value-based** | 🟢 **VFA** — Value Function Approximation | 🔵 **CFA** — Cost Function Approximation |
""")

# Detailed cards for each class
st.markdown("#### Details by Class")

tab_pfa, tab_cfa, tab_vfa, tab_dla = st.tabs([
    "🔴 PFA", "🔵 CFA", "🟢 VFA", "🟣 DLA"
])

with tab_pfa:
    st.markdown("""
    ### Policy Function Approximation

    **Idea:** Hard-code a parametric rule mapping state → decision.
    No optimisation at runtime — just evaluate a function.
    """)
    st.latex(r"X^\pi(S_t \mid \theta) = f_\theta(R_t, W_t)")
    st.markdown("""
    | Implementation | Parameters | Key Idea |
    |---|---|---|
    | `policy_PFA_threshold` | θ₁ (price), θ₂ (cap), θ₃ (trigger) | If-then rules |
    | `policy_PFA_linear` | θ₁–θ₅ (weights) | Linear signal + ReLU = 1-layer NN |
    """)
    st.markdown("""
    **When to use:** Fast prototyping, baselines, when interpretability matters.

    **Connection to ML:** PFA with gradient-tuned θ is literally *policy gradient*.
    """)

with tab_cfa:
    st.markdown("""
    ### Cost Function Approximation

    **Idea:** Solve a one-period optimisation, but modify the objective
    to implicitly value the future. The "trick" is in the proxy cost.
    """)
    st.latex(r"\min_{x_t} \; C(S_t, x_t) - \theta \cdot R_{t+1}")
    st.markdown("""
    | Implementation | Parameters | Key Idea |
    |---|---|---|
    | `policy_CFA` | θ (storage value) | LP with buffer incentive |
    | `policy_CFA_risk` | θ, κ (risk aversion) | Inflate θ when volatility is high |
    """)
    st.markdown("""
    **When to use:** When you have an LP/MIP structure and want to
    implicitly price the future without forecasting.

    **Connection to OR:** This is how reservoir and supply-chain operators
    have worked for decades — "shadow prices" and "water values".
    """)

with tab_vfa:
    st.markdown("""
    ### Value Function Approximation

    **Idea:** Learn V*(s) or Q*(s,a) offline.  At runtime,
    choose the action that minimises immediate cost + γ · V*(next state).
    """)
    st.latex(r"X^\pi(S_t) = \arg\min_{x_t} \; C(S_t, x_t) + \gamma \, \hat{V}(S_{t+1})")
    st.markdown("""
    | Implementation | Training Method | Key Idea |
    |---|---|---|
    | `policy_VFA_tabular` | Value Iteration (exact) | Full Bellman backup on grid |
    | `policy_VFA_qlearn` | Q-Learning (model-free) | ε-greedy exploration + TD updates |
    | `policy_VFA_adp` | ADP (semi-gradient TD) | Linear features φ(s)ᵀw |
    """)
    st.markdown("""
    **When to use:** When state space is manageable and you can afford
    offline training.  The trained artifact (V-table, Q-table, weights)
    is the stored "experience".

    **Connection to RL:** VFA *is* reinforcement learning.
    Value Iteration = planning, Q-Learning = model-free RL.
    """)

with tab_dla:
    st.markdown("""
    ### Direct Lookahead Approximation

    **Idea:** At each period, build and solve a multi-period optimisation
    model over forecasted futures.  Execute only the first-period decision.
    This is **Model Predictive Control (MPC)**.
    """)
    st.latex(r"X^\pi(S_t) = \arg\min_{x_{t:t+H}} \; \sum_{\tau=t}^{t+H} C(S_\tau, x_\tau, \hat{W}_\tau)")
    st.markdown("""
    | Implementation | Forecast Type | Key Idea |
    |---|---|---|
    | `policy_DLA_det` | Point forecast (1 path) | Deterministic MPC |
    | `policy_DLA_stoch` | Scenario fan (P paths) | Two-stage SP with non-anticipativity |
    | `policy_DLA_stoch_cvar` | Scenario fan + risk | Mean-CVaR objective (Rockafellar-Uryasev) |
    """)
    st.markdown("""
    **When to use:** When you have a good model of future uncertainty
    and can afford to solve an LP/MIP at each decision point.

    **Connection to stochastic programming:** DLA with scenarios and
    non-anticipativity constraints *is* two-stage SP, rolled forward.
    """)

st.divider()

# ═══════════════════════════════════════════════════════════════════════
# Footer
# ═══════════════════════════════════════════════════════════════════════

st.markdown("""
---

<div style='text-align: center; color: #666; font-size: 0.85em;'>
    <em>Voltown Sequential Decision Dashboard · Architecture Reference</em><br/>
    Built for Powell's <strong>Sequential Decision Analytics</strong> framework<br/>
    🏗️ Designed for replication — fork it, extend it, make it yours.
</div>
""", unsafe_allow_html=True)
